#!/usr/bin/env python3
"""Build a slim distribution of the Mac bench code under mac_bench_dist/
(subdir of this repo, .gitignored) and upload it to
continker/metrollm-bench-mac on HuggingFace.

The dist contains only what's needed to run run_probe.sh / run_thermal.sh on
a Mac that doesn't have access to this private repo: harness/, cases for
MARTA, data/systems/marta/, scripts/mac_bench/, pyproject.toml + uv.lock.

Usage on this Mac:
    HF_TOKEN=$(grep '^HF_TOKEN=' .env | cut -d= -f2-) \
      uv run --with huggingface_hub python scripts/mac_bench/publish_dist.py

    HF_TOKEN=... python scripts/mac_bench/publish_dist.py --dry-run     # just builds
    HF_TOKEN=... python scripts/mac_bench/publish_dist.py --skip-build  # re-upload existing dir
"""
from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

REPO_ID = "continker/metrollm-bench-mac"
REPO_TYPE = "model"  # placed under continker/ org alongside the GGUF model repos

# (source path relative to repo root, dest path inside the dist)
INCLUDES: list[tuple[str, str]] = [
    ("harness", "harness"),
    ("cases/marta_cases.json", "cases/marta_cases.json"),
    ("data/systems/marta", "data/systems/marta"),
    ("scripts/mac_bench/run_probe.sh", "scripts/mac_bench/run_probe.sh"),
    ("scripts/mac_bench/run_thermal.sh", "scripts/mac_bench/run_thermal.sh"),
    ("scripts/mac_bench/run_bench.sh", "scripts/mac_bench/run_bench.sh"),
    ("scripts/mac_bench/parse_telemetry.py", "scripts/mac_bench/parse_telemetry.py"),
    ("scripts/mac_bench/thermal_sampler.py", "scripts/mac_bench/thermal_sampler.py"),
    ("scripts/mac_bench/aggregate.py", "scripts/mac_bench/aggregate.py"),
    ("pyproject.toml", "pyproject.toml"),
    ("uv.lock", "uv.lock"),
]

README = """\
---
license: apache-2.0
language:
- en
tags:
- transit
- kiosk
- benchmark
- metrollm-bench
- apple-silicon
- mac-bench
---

# MetroLLM-Bench Mac Probe

Slim distribution of the [MetroLLM-Bench](https://github.com/continker/metrollm-bench)
hardware-envelope tools for Apple Silicon. Pulls GGUF weights from
`continker/Qwen3.5-{2B,4B,9B}-metro-v24`, runs `llama-server` locally on
Metal, executes a 15-case stratified MARTA probe (and optional sustained-load
thermal curve), and emits JSON telemetry — decode tok/s, TTFT, peak RAM,
Tier-1 deterministic accuracy + Tier-2 LLM-judge composite.

This repo exists so corporate or ephemeral Macs can `git clone` the bench
without VPN access to the private project repo.

## Prerequisites (one-time)

```bash
brew install uv llama.cpp
export ANTHROPIC_API_KEY=sk-ant-...   # for the Tier-2 LLM judge
```

If brew is unavailable: `uv` has a `curl -LsSf https://astral.sh/uv/install.sh | sh`
fallback; `llama.cpp` ships official Apple Silicon release binaries on GitHub.

## Run a 15-case probe (~10-30 min depending on Mac)

```bash
git clone https://huggingface.co/continker/metrollm-bench-mac /tmp/mac-bench
cd /tmp/mac-bench
uv sync
bash scripts/mac_bench/run_probe.sh 2b
cat results/mac_bench/*-2b-probe/telemetry.json
```

Output captures:
- `tier1_composite`, `metrollm_composite` — bench scores (deterministic + judge)
- `decode_tok_s_median` / `_p10` / `_p90` — single-stream Metal decode throughput
- `ttft_ms_median` — first-token latency end-to-end (HTTP + decode)
- `peak_rss_gb` — max RSS of `llama-server` during decode
- `runner_wallclock_s` — total wall time

## Run a sustained-load thermal curve (fanless Macs only, ~45 min)

```bash
bash scripts/mac_bench/run_thermal.sh 2b --duration 45m
```

Replays MARTA cases on a loop while `thermal_sampler.py` records tok/s + RSS
every 30 s. Captures cold → sustained → throttle behaviour. Output:
`results/mac_bench/<chip>-<ram>gb-2b-thermal/thermal_curve.{csv,json}`.

## Cleanup

```bash
rm -rf /tmp/mac-bench
```

(Optionally `brew uninstall uv llama.cpp` if you don't keep them around.)

## Per-Mac context-size requirements

`llama.cpp` allocates the full KV cache upfront at server start. Defaults
already cover the measured p99 conversation length per model:

| Size | Default ctx | KV memory | Total RAM |
|---|---:|---:|---:|
| 2B | 32 768 | 1.21 GB | ~4 GB |
| 4B | 16 384 | 2.42 GB | ~6.5 GB |
| 9B | 16 384 | 2.42 GB | ~9.2 GB (tight on 16 GB Macs) |

Override with `--ctx N` (e.g. `bash scripts/mac_bench/run_probe.sh 9b --ctx 8192`).

## License & attribution

Apache 2.0. See parent project for full citation.
"""

DIST_GITIGNORE = "# This dist is generated by scripts/mac_bench/publish_dist.py — do not commit.\n*\n!.gitignore\n"


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dist", type=Path, default=Path("mac_bench_dist"),
                   help="Local staging directory (default: mac_bench_dist/)")
    p.add_argument("--repo-id", default=REPO_ID)
    p.add_argument("--dry-run", action="store_true", help="Build dist; skip HF upload")
    p.add_argument("--skip-build", action="store_true", help="Skip rebuilding dist; just upload")
    p.add_argument("--private", action="store_true", help="Create as private repo (default public)")
    return p.parse_args()


def build_dist(src_root: Path, dist: Path) -> None:
    if dist.exists():
        shutil.rmtree(dist)
    dist.mkdir(parents=True)

    for src_rel, dst_rel in INCLUDES:
        src = src_root / src_rel
        dst = dist / dst_rel
        if not src.exists():
            print(f"WARN: missing source {src}", file=sys.stderr)
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        if src.is_dir():
            shutil.copytree(
                src, dst,
                ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache", ".DS_Store"),
            )
        else:
            shutil.copy2(src, dst)

    (dist / "README.md").write_text(README)
    (dist / ".gitignore").write_text(DIST_GITIGNORE)

    # Sanity: count files + total size
    total = 0
    n = 0
    for p in dist.rglob("*"):
        if p.is_file():
            total += p.stat().st_size
            n += 1
    print(f"Built {dist}: {n} files, {total / 1e6:.1f} MB")


def upload_dist(dist: Path, repo_id: str, private: bool) -> None:
    token = os.environ.get("HF_TOKEN")
    if not token:
        print("ERROR: HF_TOKEN not in env", file=sys.stderr)
        sys.exit(2)

    from huggingface_hub import HfApi, create_repo

    print(f"Creating/verifying {repo_id} (private={private})...")
    create_repo(repo_id, token=token, private=private, exist_ok=True, repo_type=REPO_TYPE)

    api = HfApi(token=token)
    print(f"Uploading {dist} to {repo_id}...")
    api.upload_folder(
        folder_path=str(dist),
        repo_id=repo_id,
        repo_type=REPO_TYPE,
        token=token,
        commit_message="Update Mac bench dist",
        ignore_patterns=[".gitignore", ".DS_Store"],
    )
    print(f"\nDone: https://huggingface.co/{repo_id}")


def main():
    args = parse_args()
    src_root = Path(__file__).resolve().parents[2]
    dist = (src_root / args.dist).resolve()

    if not args.skip_build:
        build_dist(src_root, dist)
    else:
        if not dist.exists():
            print(f"ERROR: --skip-build but {dist} doesn't exist", file=sys.stderr)
            sys.exit(2)

    if args.dry_run:
        print("\n[dry-run] Skipping HF upload.")
        return

    upload_dist(dist, args.repo_id, args.private)


if __name__ == "__main__":
    main()
